### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by TheKhanj** [TheKhanj/dotfiles#1]
# TODO List
- [x] refactor startup services, use something else aside from systemd 🤔
    - maybe, just a maybe pm2 might be a good option 🤔, but it's nodejs 🤮
    - if `daemontools` haven't work I'm gonna go for writing my own process
    manager. it should be quite fun too.
- [x] fix multi-keyboard issue with touchcursor
- [x] fix persian font issue once and for all
- [ ] make it simpler to install dependencies
- [x] learn bash and refactor some stuff
- [ ] automate chrome configuration. it's a chore right now to set it up each
time from scratch
- [ ] fix audio and video sync issue of screenrecord script. I don't like using
`simplescreenrecorder`. It does it job well enough, but its BLOATED.
- [ ] reduce git size
    - [ ] remove heavy commits and rebase afterward (not best thing to do I
            know. but nobody uses this except myself, so its fine)
    - [ ] move assets (although I guess there is only one) to external source

# Maybes
- [x] consider nnn? ranger is too slow
- [ ] get rid of systemd?

# Big Tasks
- [ ] use neomutt
    - how should I handle html emails as most people send emails in html
    nowadays. I don't like w3m and cli browsers. maybe I should start liking
    them...

**Comment by TheKhanj** [comment]
I'm gonna close this issue as it's not relevant anymore.
